.TH ASDL 1 "February 2024" "Version 1.0" "ASDL Manual"
.SH NAME
asdl \- ASDL language implementation
.SH SYNOPSIS
.B asdl
[\-i \fIinput_file\fR] [\-\fIo\fR \fIoutput_file\fR] [\-\fIs\fR \fIsequence_size\fR]
.SH DESCRIPTION
\fBasdl\fR is a utility for working with the Abstract Syntax Description Language (ASDL). It reads input from a file or standard input, processes it according to the ASDL specification, and writes the result to a file or standard output.

The following options are supported:
.TP
\fB\-i\fR \fIinput_file\fR
Specify the input file. If not provided, input is read from standard input.
.TP
\fB\-o\fR \fIoutput_file\fR
Specify the output file. If not provided, output is written to standard output.
.TP
\fB\-s\fR \fIsequence_size\fR
Specify the sequence size. The default is 1024.
.SH EXAMPLES
To process a file named input.asdl and output the result to output.asdl:
.PP
.B asdl -i input.asdl -o output.asdl
.SH AUTHOR
ASDL was written by John Doe <johndoe@example.com>.
.SH COPYRIGHT
Copyright \(co 2024 John Doe.

ASDL is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

ASDL is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with ASDL.  If not, see <https://www.gnu.org/licenses/>.
.SH SEE ALSO
The GitHub repository for ASDL can be found at: <https://github.com/Chubek/ZephyrASDL>

