Definitions <- Definition* EOF
Definition <- TypeID _ '=' _ Type
Type <- SumType / ProductType
ProductType <- Fields
SumType <- Constructor ( _ '|' _ Constructor)* _ ('attributes' _ Fields)?
Constructor <- ConID _ Fields?
Fields <- '(' _ Field ( _ ',' _ Field)* _ ')'
Field <- TypeID ('?' / '*')? _ ID?

ID <- ConID / TypeID
ConID <- [A-Z][a-zA-Z0-9_]*
TypeID <- [a-z][a-z0-9_]*

_ <- [ \r\n\t]+
EOF <- !.
